spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://${ZIPKIN:localhost}:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    gateway:
      discovery:
        # this enable eureka path
        # locator:
        #   enabled: true
        #   lower-case-service-id: true

        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/teamapi/**
          filters:
            - RewritePath=/teamapi/(?<path>.*), /$\{path}

    loadbalancer.ribbon.enabled: false

server:
  port: 7072

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKASERVER:localhost}:7070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
