spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://${zipkin:localhost}:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    gateway:
      discovery:
        # this enable eureka path
        locator:
          enabled: true
          lower-case-service-id: true

      # - id: sport-organization-service
      #   uri: lb://SPORT-ORGANIZATION-SERVICE
      #   predicates:
      #     - Path=/organization/**
      #   filters:
      #     - RewritePath=/organization/(?<path>.*), /$\{path}
      # - id: sport-event-service
      #   uri: lb://SPORT-EVENT-SERVICE
      #   predicates:
      #     - Path=/event/**
      #   filters:
      #     - RewritePath=/event/(?<path>.*), /$\{path}
      # use service discovery as route
    loadbalancer.ribbon.enabled: false

server:
  port: 7072

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKASERVER:localhost}:7070/eureka/
      # defaultZone: http://eurekaserver:7070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
